# Generated by Django 5.0 on 2023-12-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('instructor', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('schedule', models.FileField(upload_to='schedules/')),
            ],
        ),
    ]
