# Generated by Django 5.0 on 2023-12-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='program_type',
            field=models.CharField(default='default_program_type', max_length=100),
        ),
    ]
