# Generated by Django 5.0 on 2024-01-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_rename_username_courses_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default='default_code', max_length=100),
        ),
    ]
