# Generated by Django 5.0 on 2024-01-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_in_cart', to='Dashboard.courses'),
        ),
    ]
