# Generated by Django 5.0 on 2024-01-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_alter_cartitems_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='filled_slots',
            field=models.IntegerField(default=0),
        ),
    ]
