# Generated by Django 5.0 on 2023-12-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_and_SignUp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='default_role', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='s_id',
            field=models.CharField(default='default_id', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(default='default_department', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='program_type',
            field=models.CharField(default='default_program_type', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
