# Generated by Django 5.0 on 2023-12-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_and_SignUp', '0002_rename_student_name_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(default='default_department', max_length=150),
        ),
    ]
