# Generated by Django 5.0 on 2024-01-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_and_SignUp', '0003_alter_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
